function BlackMarketTweakData:_init_melee_weapons(tweak_data)
	self.melee_sounds = {}
	self.melee_sounds.generic = {
		hit_body = "melee_hit_body",
		hit_gen = "melee_hit_gen",
	}
	self.melee_sounds.fist = {
		equip = "fist_equip",
		hit_air = "knife_hit_air",
		hit_body = "punch_gunstock_1p",
		hit_gen = "melee_hit_gen",
	}
	self.melee_sounds.knife = {
		equip = "knife_equip",
		hit_air = "knife_hit_air",
		hit_body = "knife_hit_body",
		hit_gen = "knife_hit_gen",
		killing_blow = "knife_killing_blow",
	}
	self.melee_sounds.machete = {
		equip = "knife_equip",
		hit_air = "knife_hit_air",
		hit_body = "machete_hit_body",
		hit_gen = "knife_hit_gen",
		killing_blow = "machete_killing_blow",
	}

	local MELEE_SPEED_INSTANT = 0
	local MELEE_SPEED_NORMAL = 1
	local MELEE_HEADSHOT_MULTIPLIER = 1.5

	self.melee_weapons = {}
	self.melee_weapons.weapon = {
		expire_t = 0.6,
		free = true,
		instant = true,
		name_id = "bm_melee_weapon",
		repeat_expire_t = 0.6,
		type = "weapon",
		sounds = self.melee_sounds.generic,
		stats = {
			max_damage = 75,
			max_damage_effect = 1,
			min_damage = 75,
			min_damage_effect = 1,
			range = 150,
			weapon_type = "blunt",
			charge_time = MELEE_SPEED_INSTANT,
		},
	}
	self.melee_weapons.fists = {
		anim_global_param = "melee_fist",
		expire_t = 1,
		free = true,
		melee_charge_shaker = "player_melee_charge_fist",
		melee_damage_delay = 0.2,
		name_id = "bm_melee_fists",
		repeat_expire_t = 0.55,
		type = "fists",
		anim_attack_vars = {
			"var1",
			"var2",
			"var3",
			"var4",
		},
		sounds = self.melee_sounds.fist,
		stats = {
			concealment = 30,
			max_damage = 92,
			max_damage_effect = 2,
			min_damage = 50,
			min_damage_effect = 3,
			range = 150,
			remove_weapon_movement_penalty = true,
			weapon_type = "blunt",
			charge_time = MELEE_SPEED_NORMAL,
		},
	}
	self.melee_weapons.m3_knife = {
		decal_effect = "knife",
		desc_id = "bm_melee_m3_knife_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.223,
		name_id = "bm_melee_m3_knife",
		repeat_expire_t = 0.6,
		stance = "m3",
		third_unit = "units/vanilla/weapons/wpn_third_mel_m3_knife/wpn_third_mel_m3_knife",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_m3_knife/wpn_fps_mel_m3_knife",
		usage_anim = "c45",
		weapon_hold = "m3",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 10,
			distance_offset = -100,
			height_offset = -8,
			rotation_offset = -2,
			initial_rotation = {
				pitch = 20,
				roll = 160,
				yaw = 90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.robbins_dudley_trench_push_dagger = {
		decal_effect = "knife",
		desc_id = "bm_melee_robbins_dudley_trench_push_dagger_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_robbins_dudley_trench_push_dagger",
		repeat_expire_t = 0.6,
		reward_image = "units/vanilla/weapons/wpn_fps_mel_robbins_dudley_trench_push_dagger/robbins_dudley_trench_push_dagger_hud",
		stance = "robbins_dudley_trench_push_dagger",
		third_unit = "units/vanilla/weapons/wpn_third_mel_robbins_dudley_trench_push_dagger/wpn_third_mel_robbins_dudley_trench_push_dagger",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_robbins_dudley_trench_push_dagger/wpn_fps_mel_robbins_dudley_trench_push_dagger",
		usage_anim = "c45",
		weapon_hold = "robbins_dudley_trench_push_dagger",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 12,
			distance_offset = -100,
			height_offset = -12,
			rotation_offset = 4,
			initial_rotation = {
				pitch = 0,
				roll = 0,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.german_brass_knuckles = {
		desc_id = "bm_melee_german_brass_knuckles_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_german_brass_knuckles",
		repeat_expire_t = 0.6,
		reward_image = "units/vanilla/weapons/wpn_fps_mel_german_brass_knuckles/german_brass_knuckles_hud",
		stance = "brass_knuckles",
		third_unit = "units/vanilla/weapons/wpn_third_mel_german_brass_knuckles/wpn_third_mel_german_brass_knuckles",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_german_brass_knuckles/wpn_fps_mel_german_brass_knuckles",
		usage_anim = "c45",
		weapon_hold = "brass_knuckles",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 14,
			distance_offset = -130,
			height_offset = -9,
			rotation_offset = 4,
			initial_rotation = {
				pitch = 0,
				roll = 0,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.fist,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.lockwood_brothers_push_dagger = {
		desc_id = "bm_melee_lockwood_brothers_push_dagger_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_lockwood_brothers_push_dagger",
		repeat_expire_t = 0.6,
		reward_image = "units/vanilla/weapons/wpn_fps_mel_lockwood_brothers_push_dagger/lockwood_brothers_push_dagger_hud",
		stance = "lockwood_brothers_push_dagger",
		third_unit = "units/vanilla/weapons/wpn_third_mel_lockwood_brothers_push_dagger/wpn_third_mel_lockwood_brothers_push_dagger",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_lockwood_brothers_push_dagger/wpn_fps_mel_lockwood_brothers_push_dagger",
		usage_anim = "c45",
		weapon_hold = "lockwood_brothers_push_dagger",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 13,
			distance_offset = -120,
			height_offset = -11,
			rotation_offset = 1,
			initial_rotation = {
				pitch = 0,
				roll = 0,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			effect = "knife",
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.bc41_knuckle_knife = {
		decal_effect = "knife",
		desc_id = "bm_melee_bc41_knuckle_knife_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_bc41_knuckle_knife",
		repeat_expire_t = 0.6,
		reward_image = "units/vanilla/weapons/wpn_fps_mel_bc41_knuckle_knife/bc41_knuckle_knife_hud",
		stance = "bc41_knuckle_knife",
		third_unit = "units/vanilla/weapons/wpn_third_mel_bc41_knuckle_knife/wpn_third_mel_bc41_knuckle_knife",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_bc41_knuckle_knife/wpn_fps_mel_bc41_knuckle_knife",
		usage_anim = "c45",
		weapon_hold = "bc41_knuckle_knife",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 13,
			distance_offset = -120,
			height_offset = -9,
			rotation_offset = 2,
			initial_rotation = {
				pitch = 0,
				roll = 0,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.km_dagger = {
		desc_id = "bm_melee_km_dagger_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "melee",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_km_dagger",
		repeat_expire_t = 0.6,
		stance = "km_dagger",
		third_unit = "units/vanilla/weapons/wpn_third_mel_km_dagger/wpn_third_mel_km_dagger",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_km_dagger/wpn_fps_km_dagger",
		usage_anim = "c45",
		weapon_hold = "km_dagger",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		dlc = DLCTweakData.DLC_NAME_SPECIAL_EDITION,
		gui = {
			display_offset = 9,
			distance_offset = -75,
			height_offset = -8,
			rotation_offset = -12,
			initial_rotation = {
				pitch = -165,
				roll = 15,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.marching_mace = {
		decal_effect = "knife",
		desc_id = "bm_melee_marching_mace_desc",
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "marching_mace",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_marching_mace",
		repeat_expire_t = 0.6,
		stance = "marching_mace",
		third_unit = "units/vanilla/weapons/wpn_third_mel_marching_mace/wpn_third_mel_marching_mace",
		transition_duration = 0,
		type = "knife",
		unit = "units/vanilla/weapons/wpn_fps_mel_marching_mace/wpn_fps_mel_marching_mace",
		usage_anim = "c45",
		weapon_hold = "marching_mace",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		dlc = DLCTweakData.DLC_NAME_SPECIAL_EDITION,
		gui = {
			display_offset = -6,
			distance_offset = 60,
			height_offset = -10,
			rotation_offset = -30,
			initial_rotation = {
				pitch = 30,
				roll = 0,
				yaw = -90,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.knife,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}
	self.melee_weapons.lc14b = {
		decal_effect = "knife",
		desc_id = "bm_melee_lc14b_desc",
		dismember_chance = 0.5,
		exit_run_speed_multiplier = 1,
		expire_t = 0.75,
		hold = "machete",
		melee_charge_shaker = "player_melee_charge",
		melee_damage_delay = 0.1,
		name_id = "bm_melee_lc14b",
		repeat_expire_t = 0.6,
		reward_image = "units/event_001_halloween/weapons/wpn_fps_mel_lc14b/wpn_fps_mel_lc14b_hud",
		stance = "machete",
		third_unit = "units/event_001_halloween/weapons/wpn_third_mel_lc14b/wpn_third_mel_lc14b",
		transition_duration = 0,
		type = "knife",
		unit = "units/event_001_halloween/weapons/wpn_fps_mel_lc14b/wpn_fps_mel_lc14b",
		usage_anim = "c45",
		weapon_hold = "machete",
		weapon_movement_penalty = 1,
		align_objects = {
			"a_weapon_right",
		},
		animations = {
			equip_id = "equip_welrod",
		},
		gui = {
			display_offset = 8,
			distance_offset = -80,
			height_offset = -4,
			rotation_offset = -10,
			initial_rotation = {
				pitch = 10,
				roll = 160,
				yaw = 100,
			},
		},
		headshot_multiplier = MELEE_HEADSHOT_MULTIPLIER,
		sounds = self.melee_sounds.machete,
		stats = {
			concealment = 30,
			max_damage = 150,
			max_damage_effect = 1,
			min_damage = 80,
			min_damage_effect = 1,
			range = 185,
			remove_weapon_movement_penalty = true,
			weapon_type = "sharp",
			charge_time = MELEE_SPEED_NORMAL,
		},
		timers = {
			equip = 0.25,
			reload_empty = 1.65,
			reload_not_empty = 1.25,
			unequip = 0.5,
		},
		use_data = {
			equip = {
				align_place = "right_hand",
			},
			selection_index = tweak_data.weapon.WEAPON_SLOT_MELEE,
			unequip = {
				align_place = "back",
			},
		},
	}

	self:_add_desc_from_name_macro(self.melee_weapons)
end
